#!/usr/bin/env bash

DMBROWSER="${BROWSER:-firefox}"

# Sourcing pywal for dmenu colors
source "${HOME}/.cache/wal/colors.sh"

while [ -z "$query" ]; do
    query=$(echo "$engine" | dmenu -fn "Jetbrains Mono:size=11" -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15" -p 'Enter search query:') "$@" || exit
done

$DMBROWSER "$query"
